# Generated by Django 4.1.7 on 2023-03-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=40)),
                ('cat_temperament', models.CharField(max_length=100)),
                ('cat_origin', models.CharField(max_length=20)),
                ('cat_description', models.CharField(max_length=300)),
                ('cat_wikipedia', models.URLField()),
                ('cat_image', models.URLField()),
            ],
        ),
    ]
